namePrefix: prod-
namespace: prod-guide2go
commonLabels:
  app: prod-guide2go
  env: prod
resources:
- ../../base
images:
- name: chuchodavids/guide2go:stable
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
