namePrefix: dev-
namespace: dev-guide2go
commonLabels:
  app: dev-guide2go
  env: dev
resources:
- ../../base
images:
- name: chuchodavids/guide2go:development
  newName: chuchodavids/guide2go
  newTag: "1678998793"
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
